spring:
  application:
    name: index-config-server
  cloud:
    config:
      label: master   ### 表示 分支
      server:
        git:
          uri: https://github.com/laogui1999/trendConfig/  ### 表示 git 地址
          searchPaths: respo   ###表示目录：
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/